networks:
  app:
    driver: bridge

services:
  mariadb:
    networks:
      - app
    build: ./requirements/mariadb/
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - DB_USER=$DB_USER
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mariadb/
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5m
      start_interval: 5s
  wordpress:
    build: ./requirements/wordpress/
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
      - WP_ADMIN_USER=$WP_ADMIN_USER
      - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
      - WP_URL=$WP_URL
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/wp/
  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    networks:
      - app
    volumes:
      - wp-data:/wp/

volumes:
  db-data:
  wp-data:
