networks:
  app:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    networks:
      - app
    build: ./requirements/mariadb/
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - DB_USER=$DB_USER
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mariadb/
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 3
      # Start period: failure during that period will not be counted towards the maximum number of retries.
      # If a health check succeeds during the start period, the container is considered started.
      start_period: 5m
      start_interval: 5s
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
      - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
      - WP_ADMIN_USER=$WP_ADMIN_USER
      - WP_URL=$WP_URL
      - WP_USER=$WP_USER
      - WP_USER_EMAIL=$WP_USER_EMAIL
      - WP_USER_PASSWORD=$WP_USER_PASSWORD
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app
    restart: unless-stopped
    volumes:
      - wp-data:/wp/
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - app
    restart: unless-stopped
    volumes:
      - wp-data:/wp/

volumes:
  db-data:
    driver_opts:
      device: /home/copireyr/data/mariadb
      o: bind
      type: none
  wp-data:
    driver_opts:
      device: /home/copireyr/data/wp
      o: bind
      type: none
